post-assembly-quality-control training
galaxyproject/training-material pull request #3908
Opened 2023-02-22 12:01 UTC by GitFab93

2023-03-02 09:17 UTC, shiltemann commented
Hi @GitFab93! Thanks for your draft PR, please let us know if you run into any problems, have any questions, or if there are certain parts of this you would like us to have a look at already :)

2023-03-22 15:57 UTC, gallardoalba commented on topics/assembly/tutorials/post-assembly-quality-control/tutorial.md
> +Correctness or accuracy of an assembly can be gauged by checking base-level and structural errors. This can be done by mapping the raw sequencing reads to the target assembly and then calculating the
I would introduce each tool in their specific section, instead of including that information in the introducion.

2023-03-22 15:57 UTC, gallardoalba commented on topics/assembly/tutorials/post-assembly-quality-control/tutorial.md
> +>
Datasets need to be updated to Zenodo: https://zenodo.org/

2023-06-22 13:09 UTC, gallardoalba approved these changes

2023-06-22 16:18 UTC, gallardoalba requested changes

2023-06-22 16:18 UTC, gallardoalba commented on topics/assembly/tutorials/ERGA-post-assembly-QC/tutorial.md
> +##### Case 1: ***Chondrosia reniformis***:
```suggestion
<strong>Case 1: <em>Chondrosia reniformis</em></strong>
```

2023-06-22 16:18 UTC, gallardoalba commented on topics/assembly/tutorials/ERGA-post-assembly-QC/tutorial.md
> +##### Case 2: ***Erythrolamprus reginae***:
```suggestion
<strong>Case 2: <em>Erythrolamprus reginae</em></strong>
```

2023-06-22 16:18 UTC, gallardoalba commented on topics/assembly/tutorials/ERGA-post-assembly-QC/tutorial.md
> +##### Case 3: ***Eschrichtius robustus***:
```suggestion
<strong>Case 3: <em>Eschrichtius robustus</em></strong>
```

2023-06-22 16:18 UTC, gallardoalba commented on topics/assembly/tutorials/ERGA-post-assembly-QC/tutorial.md
> +The assembly used in this tutorial correspond to the curated primary assembly generated by the [VGP project](https://vertebrategenomesproject.org/), based on 29x Pacbio HiFi data, by using the [VGP a
```suggestion
The assembly used in this tutorial correspond to the curated primary assembly generated by the [VGP project](https://vertebrategenomesproject.org/), based on 29x Pacbio HiFi data, by using the [VGP assembly pipeline]({% link topics/assembly/tutorials/vgp_genome_assembly/tutorial.html %}). 
```

2023-06-22 16:18 UTC, gallardoalba commented on topics/assembly/tutorials/ERGA-post-assembly-QC/tutorial.md
> +The assembly used in this tutorial correspond to the curated primary assembly generated by the [VGP project](https://vertebrategenomesproject.org/), based on 34x Pacbio HiFi and Arima2 Hi-C data, by
```suggestion
The assembly used in this tutorial correspond to the curated primary assembly generated by the [VGP project](https://vertebrategenomesproject.org/), based on 34x Pacbio HiFi and Arima2 Hi-C data, by using the [VGP assembly pipeline]({% link topics/assembly/tutorials/vgp_genome_assembly/tutorial.html %}). 
```

2023-06-22 16:18 UTC, gallardoalba commented on topics/assembly/tutorials/ERGA-post-assembly-QC/tutorial.md
> +>    {: .details}
```suggestion
>    {: .comment}
```

2023-06-22 16:18 UTC, gallardoalba commented on topics/assembly/tutorials/ERGA-post-assembly-QC/tutorial.md
> +1. {% tool [gfastats](toolshed.g2.bx.psu.edu/repos/bgruening/gfastats/gfastats/1.3.6+galaxy0) %} with the following parameters:
```suggestion
> 1. {% tool [gfastats](toolshed.g2.bx.psu.edu/repos/bgruening/gfastats/gfastats/1.3.6+galaxy0) %} with the following parameters:
```

2023-06-22 16:20 UTC, gallardoalba submitted a review, later dismissed

2023-06-22 16:37 UTC, gallardoalba commented
Hi @hexylena, could you have a look at the linting? Not sure why it is failing. Thanks a lot!

2023-06-22 19:44 UTC, hexylena commented
@gallardoalba did you check the linting logs? there are some messages there. I wish it would make the comments directly but unfortunately GitHub permissions prevents it.

- workflow is missing a test, license, creator information
- some references are missing a doi
- a link uses `here` as the text which isn't accessible
- two broken links

they should also appear in the "files changed" view, but again, unfortunately not as a proper comment due to permissions.

2023-06-23 09:39 UTC, gallardoalba commented
I think I found the problem, it should be fixed here https://github.com/GitFab93/training-material/pull/33

2023-06-23 12:16 UTC, gallardoalba commented on topics/assembly/tutorials/ERGA-post-assembly-QC/tutorial.bib
> +  url={https://dalspace.library.dal.ca/bitstream/handle/10222/77605/VOLUME%2025-NUMBERS%201-3-1998-PAGE%2057.pdf}
```suggestion
  url={https://dalspace.library.dal.ca/bitstream/handle/10222/77605/VOLUME%2025-NUMBERS%201-3-1998-PAGE%2057.pdf},
```

2023-06-23 12:49 UTC, gallardoalba commented on topics/assembly/tutorials/ERGA-post-assembly-QC/workflows/main_workflow.ga
> +        },
```suggestion
```

2023-06-23 13:35 UTC, gallardoalba approved these changes

2023-06-23 16:06 UTC, merged